<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<div class="filter-list" id="filter-price">

    <a class="filter-choose" href="javascript:void(0);"><span class="123">PRICE</span>
        <span class="filter-sign"></span></a>

    <div class="filter-box list-price">
        <div class="box-price">

            <?php foreach ($filterItems as $filterItem): ?>
                <li class="item">
                    <?php if ($filterItem->getCount() > 0): ?>
                        <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                            <?= $filterItem->getLabel() ?>
                            <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                                <span class="count"><?= $filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1): ?> <?= __('item') ?><?php else: ?><?php endif; ?></span></span>
                            <?php endif; ?>
                        </a>
                    <?php else: ?>
                        <?= $filterItem->getLabel() ?>
                        <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                            <span class="count"><?= $filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1): ?><?= __('item') ?><?php else: ?><?= __('items') ?><?php endif; ?></span></span>
                        <?php endif; ?>
                    <?php endif; ?>
                </li>
            <?php endforeach ?>
        </div>
        <input type="submit" value="APPLY" class="filter-submit">
    </div>

</div>