<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
$curUrl = explode("?", $urlInterface->getCurrentUrl())[0];
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter">

        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>

            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
        <?php if (!$wrapOptions): ?>
            <strong role="heading" aria-level="2"
                    class="block-subtitle filter-subtitle"><?= __('Shopping Options') ?></strong>
            <dl class="filter-options" id="narrow-by-list">
                <?php $wrapOptions = true;
                endif; ?>
                <?php if ($filter->getItemsCount()): ?>
                    <dt role="heading" aria-level="3"
                        class="filter-options-title"><?php echo $block->escapeHtml(__($filter->getName())) ?></dt>
                    <dd class="filter-options-content"><?= $block->getChildBlock('renderer')->render($filter); ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
            </dl>
        <?php endif; ?>

            <div class="fitter-list">
                <form action="<?= $curUrl . '' ?>" method="get">
                    <label class="sel no-icon-mobile checkbox">
                        <a class="fitter-choose" href="javascript:void(0);"><span class="123">Color</span>
                            <span class="fitter-sign"></span></a>
                    </label><br>
                    <div class="fitter-box">
                        <label class="sel no-icon-mobile checkbox">
                            <input id="check_0" type="checkbox" name="color" value="7">
                            <span class="Black">Black</span>
                        </label><br>
                        <label class="sel no-icon-mobile checkbox">
                            <input id="check_0" type="checkbox" name="color" value="8">
                            <span class="White">White</span>
                        </label><br>
                        <label class="sel no-icon-mobile checkbox">
                            <input id="check_0" type="checkbox" name="color" value="9">
                            <span class="Red">Red</span>
                        </label><br>
                        <input type="submit" value="APPLY">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function ($) {
            $(document).ready(function ($) {

                $('.fitter-list .fitter-choose').click(function () {
                    var isOpen = $('.fitter-list .fitter-sign').hasClass("open");
                    if (isOpen) {
                        $('.fitter-list .fitter-sign').removeClass("open");
                        $('.fitter-list .fitter-box').removeClass("active");
                    } else {
                        $('.fitter-list .fitter-sign').removeClass('open');
                        $('.fitter-list .fitter-sign').addClass("open");
                        $('.fitter-list .fitter-box').addClass("active");
                    }
                });

            });
        });
    </script>


<?php endif; ?>





