<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of \Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
?>

<div class="col-1025">
    <div class="footer content">
        <div class="row" id="footer-default" data-mobile="">
            <!--1st-->
            <div class="col-sm-3 box-footer">
                <h4 class="title-section-footer">ABOUT US</h4>
                <a href="javascript:void(0);" class="click-ft-item"><span class="footer-scroll"></span></a>
                <ul class="footer links ft-sub-item">
                    <li class="nav item">
                        <a href="/about">Company</a>
                    </li>
                    <li class="nav item">
                        <a href="/contact-us">Contact Us</a>
                    </li>
                </ul>
            </div>
            <!--2nd-->
            <div class="col-sm-3 box-footer">
                <h4 class="title-section-footer">CARE</h4>
                <a href="javascript:void(0);" class="click-ft-item"><span class="footer-scroll"></span></a>
                <ul class="footer links ft-sub-item">
                    <li class="nav item">
                        <a href="/size_guide">Size Guide</a>
                    </li>
                    <li class="nav item">
                        <a href="/ship_return">Shipping and Return</a>
                    </li>
                    <li class="nav item">
                        <a href="/privacy-policy">Privacy Policy</a>
                    </li>
                    <div class="cc_footer">
                        <img src="/pub/media/images/icon/cc1.png" />
                        <img src="/pub/media/images/icon/cc2.png" />
                    </div>
                </ul>
            </div>
            <!--3rd-->
            <div class="col-sm-3 box-footer">
                <h4 class="title-section-footer">JOIN OUR MAILING LIST</h4>
                <a href="javascript:void(0);" class="click-ft-item"><span class="footer-scroll"></span></a>
                <ul class="footer links ft-sub-item">
                    <li>
                        <p style="color:gray">Enter your email address below:</p>
                    </li>
                    <li>
                        <div class="block newsletter">
                            <div class="content">
                                <form class="form subscribe" novalidate="novalidate"
                                      action="/newsletter/subscriber/new/" method="post"
                                      id="newsletter-validate-detail">
                                    <div class="field newsletter">
                                        <div class="control">
                                            <input name="email" type="email" id="newsletter"
                                                   data-validate="{required:true, 'validate-email':true}">
                                        </div>
                                    </div>
                                    <!-- <div class="actions"> -->
                                    <div>
                                        <button class="action subscribe primary" title="Subscribe" type="submit">
                                            <span>SUBMIT</span>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-sm-3 box-footer">
                <h4 class="title-section-footer">FOLLOW US</h4>
                <a href="javascript:void(0);" class="click-ft-item"><span class="footer-scroll"></span></a>
                <ul class="footer links ft-sub-item">
                    <div class="socialFooter">
                        <a href="https://www.instagram.com/wowcouture_usa/" target="_blank">
                            <img src="<?= $mediaUrl ?>images/icon/social/sns_insta.png"/>
                        </a>
                        <a href="https://www.facebook.com/wowcouture/" target="_blank">
                            <img src="<?= $mediaUrl ?>images/icon/social/sns_fb.png"/>
                        </a>
                        <a href="https://www.pinterest.com/wowcouture_usa/wow-couture/" target="_blank">
                            <img src="<?= $mediaUrl ?>images/icon/social/sns_pin.png"/>
                        </a>
                    </div>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="copyRight">
    <p>©2016 WOWCOUTURE Wow Couture</p>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function ($) {
            var $window = $(window);

            $('.click-ft-item').click(function () {
                var curWidth = $window.width();
                if (curWidth < 768) {
                    var isOpen = $(this).hasClass("open");
                    if (isOpen) {
                        $(this).removeClass("open");
                    } else {
                        $('#footer-default .open').removeClass('open');
                        $(this).addClass("open");
                    }
                }
            });
            function resetFooter() {
                $('#footer-default .click-ft-item').removeClass("open");
            }

            function checkWidth() {
                var windowSize = $window.width();
                var currDevice = $('#footer-default').attr("data-mobile");
                var isMobile = (windowSize < 768) ? true : false;
                if (currDevice == "1") {
                    if (!isMobile) resetFooter();
                } else if (currDevice == "0") {
                    if (isMobile) resetFooter();
                }
                (isMobile) ? $('#footer-default').attr("data-mobile", "1") : $('#footer-default').attr("data-mobile", "0");
            }

            // Resize
            checkWidth();
            $(window).resize(checkWidth);
        });
    });
</script>