<?php
$objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
$categoryFactory = $objectManagerr->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categoryy = $categoryFactory->create()
    ->addAttributeToFilter('is_active', '1')
    ->addAttributeToSelect('name');

$category_ar = [];
$rootId = 0;
$first = false;
foreach ($categoryy as $cate) {

    $curId = intval($cate->getId());
    $parentId = intval($cate->getParentID());

    if ($parentId == 1 && !$first) {
        $rootId = $curId;
        $first = true;
    }

    if (isset($parentId) && $rootId > 0 && $parentId == $rootId) {
        $category_ar[$curId] = [
            "id" => $curId,
            "name" => $cate->getName(),
            "url" => $cate->getURL(),
            "parentId" => $parentId,
            "isActive" => 1,
            "subCategories" => []
        ];
    } else if ($parentId != $rootId && $first && $parentId != 1) {
        if (isset($category_ar[$parentId])) {
            $len = count($category_ar[$parentId]["subCategories"]);
            $category_ar[$parentId]["subCategories"][$len] = [
                "id" => $curId,
                "name" => $cate->getName(),
                "url" => $cate->getURL(),
                "parentId" => $parentId,
                "isActive" => 1
            ];
        }
    }
}
?>

<div class="block filter categorySidebar" id="layered-filter-block">
    <h4 class="title-sidaber title-">CATEGORIES</h4>
    <span class="sign"></span>
    <div id='cssmenu'>
        <ul>
            <?php
            foreach ($category_ar as $key) {
                $hasSub = (is_array($key["subCategories"]) && count($key["subCategories"]) > 0) ? true : false;
                ?>
                <li class='has-sub'>
                    <!--                    <a href="-->
                    <?php //echo ($hasSub) ? 'javascript:void(0);' : $key["url"] ?><!--" title="-->
                    <? //= $key['name'] ?><!--">-->
                    <a href="<?php echo $key["url"]; ?>" title="<?= $key['name'] ?>">
                    <span>
                        <?php
                        echo $key['name'];
                        ?>
                    </span>
                    </a>

                    <?php if ($hasSub) { ?>
                        <span class="sign"></span>
                        <ul class="sub-active">
                            <?php foreach ($key["subCategories"] as $subCate) { ?>
                                <li>
                                    <a href="<?= $subCate['url'] ?>" title="<?= $subCate['name'] ?>">
                                        <span><?= $subCate['name'] ?></span>
                                    </a>
                                </li>
                            <?php } ?>
                        </ul>
                    <?php } ?>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function ($) {
            var $window = $(window);

            $('.has-sub').click(function () {
                var curWidth = $window.width();
                if (curWidth < 768) {
                    var isOpen = $(this).hasClass("open");
                    if (isOpen) {
                        $(this).removeClass("open");
                    } else {
                        $('#cssmenu .open').removeClass('open');
                        $(this).addClass("open");
                    }
                }
            });

            $('#layered-filter-block > .sign').click(function () {
                var isOpen = $(this).hasClass("open");
                if (isOpen) {
                    $(this).removeClass("open");
                    $('#layered-filter-block #cssmenu').removeClass("active");
                } else {
                    $('#layered-filter-block .open').removeClass('open');
                    $(this).addClass("open");
                    $('#layered-filter-block #cssmenu').addClass("active");
                }
            });
            function resetFooter() {
                $('#cssmenu .has-sub').removeClass("open");
            }

            function checkWidth() {
                var windowSize = $window.width();
                var currDevice = $('#cssmenu').attr("data-mobile");
                var isMobile = (windowSize < 768) ? true : false;
                if (currDevice == "1") {
                    if (!isMobile) resetFooter();
                } else if (currDevice == "0") {
                    if (isMobile) resetFooter();
                }
                (isMobile) ? $('#cssmenu').attr("data-mobile", "1") : $('#cssmenu').attr("data-mobile", "0");
            }

            // Resize
            checkWidth();
            $(window).resize(checkWidth);
        });
    });
</script>
