<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

$sa = $_objectManager->get('Sahy\Banner\Block\Frontend\Banners');
$banners = $sa->getAllBannerByType($sa::TYPE_HOME_BANNER);
$_sub = $sa->getAllBannerByType($sa::TYPE_SUB_BANNER);
?>


<div class="col-1025">
    <div class="row subBanner">
        <div class="col-xs-12 col-sm-12 sumHome">CHECK OUT OUR LATEST STYLE GUIDE</div>
        <?php $i = 1; ?>
        <?php foreach($_sub as $item) { ?>
            <?php if ($i <= 2) { ?>
                <div class="col-xs-12 col-sm-6">
                    <a href="<?= $item['link'] ?>">
                        <img class="img-full" src="<?= $mediaUrl . $item['image'] ?>"/>
                    </a>
                </div>
            <?php } ?>
            <?php if ($i > 2) { ?>
                <div class="col-xs-12 col-sm-12">
                    <a href="<?= $item['link'] ?>">
                        <img class="img-full" src="<?= $mediaUrl . $item['image'] ?>"/>
                    </a>
                </div>
            <?php } ?>
            <?php $i++; ?>
        <?php } ?>
    </div>
    <div class="clearfix pad30"></div>
    <!-- # Sub Banner  -->

    <!-- SNS SIVA -->
    <?php
    function fetchData($url){
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_TIMEOUT, 20);
        $result = curl_exec($ch);
        curl_close($ch);
        return $result;
    }
    $result = fetchData("https://api.instagram.com/v1/users/1283635372/media/recent?access_token=1283635372.1677ed0.5bf79b6b394e45ca810bc2c190f517ca");
    //echo $result;
    $result = json_decode($result);
    ?>

    <p class="headHome">#WOWCOUTURE</p>
    <div class="sumHome">Check out #WOWCouture to see who's wearing us now -- on the street and the Red Carpet!</div>

    <div id="snsSiva" class="carousel slide productSlider" data-ride="carousel" data-interval="false">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <!-- Items -->
            <?php $i = 1; $max = count($result->data); ?>
            <?php foreach ($result->data as $post) { ?>
                <?php if ($i % 6 == 1) { ?>
                    <div class="item <?= ($i == 1) ? ' active' : '' ?>">
                    <div class="row">
                <?php } ?>

                <div class="col-xs-6 col-sm-4 col-md-2" style="padding-bottom: 10px; padding-top: 10px">
                    <a href="<?= $post->link ?>">
                        <div class="img-resp img100">
                            <img src="<?= $post->images->thumbnail->url ?>"/>
                        </div>
                    </a>
                </div>
                <?php if ($i % 6 == 0 || $i == $max ) { ?>
                    </div>
                    </div>
                <?php } ?>
                <?php $i++; ?>
            <?php } ?>
        </div>
        <!-- Controls -->
        <a href="#snsSiva" role="button" data-slide="prev">
            <div class="prevButtonWrap slideCtr" aria-hidden="true">
                <img src="<?= $mediaUrl ?>images/icon/pLeft.png"/>
            </div>
        </a>
        <a href="#snsSiva" role="button" data-slide="next">
            <div class="nextButtonWrap slideCtr" aria-hidden="true">
                <img src="<?= $mediaUrl ?>images/icon/pRight.png"/>
            </div>
        </a>
    </div>

</div>
