<!--<script type="text/javascript" src="/pub/js/instagram/jquery-2.1.4.min.js"></script>-->
<script type="text/javascript" src="/pub/js/instagram/instafeed.min.js"></script>
<!--<script type="text/javascript" src="/pub/js/instagram/owl.carousel.min.js"></script>-->

<div class="grid_12">
  <div class="box-instagram">
    <div id="instafeed" class="owl-carousel owl-theme" style="width: 100%;">
    </div>
  </div>
</div>
<script type="text/javascript">
	require(['jquery','owlcarousel'],function($){
	$(document).ready(function(){
    var feed = new Instafeed({
        userId: 1283635372,
		//userId: 94764,
        get: 'user',
		tagName: 'WOWCOUTURE_USA',
        accessToken: '1283635372.1677ed0.5bf79b6b394e45ca810bc2c190f517ca',
		//accessToken: '94764.1677ed0.c6256a27eddf41709ddf29af3469a4e5',
	limit: 6,
	sortBy:'random',
        template: '<div class="items"><a href="{{link}}"><img src="{{image}}" /></a></div>',
        resolution: 'low_resolution',
        after: function () {
          var owl = $('#instafeed');
          owl.owlCarousel({
            navigation:true,
			items:4
          });
        }
    });
    feed.run();    
});
	});
</script>
