<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="custom.css">
    <link rel="stylesheet" type="text/css" href="style-m.css">
    <link rel="stylesheet" type="text/css" href="bootstrap.min.css">
    <style>
    	
    </style>
</head>
<body>
<!-- <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
    <div class="hovereffect">
        <img class="img-responsive" src="http://placehold.it/350x200" alt="">
        <div class="overlay">
            <h2>Hover effect 2</h2>
            <a class="info" href="#">link here</a>
        </div>
    </div>
</div> -->


<!--real code-->
		<h3 id="lookbook_text">LOOKBOOK</h3>
		<img class="img-responsive lookbook_cover" src="http://52.38.9.201/pub/media/banners/SIVA-WOMENS.jpg" alt="" />

		<div class="hovereffect">
			<img class="img-full img-responsive" src="http://52.38.9.201/pub/media/banners/GOLDBANNER-6-3-16.png" alt="" />
			<div class="overlay">
	            <a class="info view_lookbook" href="#">View Lookbook</a>
	        </div>
		</div>
		
		<div class="hovereffect">
			<img class="img-full img-responsive" src="http://52.38.9.201/pub/media/banners/GOLD_BANNER.jpg" alt="" />
			<div class="overlay">
	            <a class="info view_lookbook" href="#">View Lookbook</a>
       		</div>
		</div>
		
		<div class="hovereffect">
			<img class="img-full img-responsive" src="http://52.38.9.201/pub/media/banners/GOLDBANNER-6-3-16.png" alt="" />
			<div class="overlay">
	            <a class="info view_lookbook" href="#">View Lookbook</a>
       		</div>
		</div>
		
		<div class="hovereffect">
			<img class="img-full img-responsive" src="http://52.38.9.201/pub/media/banners/GOLD_BANNER.jpg" alt="" />
			<div class="overlay">
	            <a class="info view_lookbook" href="#">View Lookbook</a>
        	</div>
		</div>
	
</body>
</html>