<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php
    $urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
    $curUrl = explode("?", $urlInterface->getCurrentUrl())[0];

    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of \Magento\Framework\App\ObjectManager
    $storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
    $currentStore = $storeManager->getStore();
    $baseUrl = $currentStore->getBaseUrl();
    $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    $linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

?>

<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getUseContainer()): ?>
        <div class="pager">
    <?php endif ?>

    <?php if ($block->getShowAmounts()): ?>
        <p class="toolbar-amount">
            <span class="toolbar-number">
            <?php if ($block->getLastPageNum()>1): ?>
                <?= __('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum()) ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?= __('%1 Item', $block->getTotalNum()) ?>
            <?php else: ?>
                <?= __('%1 Item(s)', $block->getTotalNum()) ?>
            <?php endif; ?>
            </span>
        </p>
    <?php endif ?>

    <?php if ($block->getLastPageNum()>1): ?>
        <div class="pages">
            <strong class="label pages-label" id="paging-label"><?= __('Page') ?></strong>
            <ul class="items pages-items" aria-labelledby="paging-label">
                <?php if (!$block->isFirstPage()): ?>
                    <li class="item pages-item-previous">
                        <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                        <a class="<?= $text ? 'link ' : 'action '?> previous" href="<?= $block->getPreviousPageUrl() ?>" title="<?= $text ? $text : __('Previous') ?>">
                            <span class="label"><?= __('Page') ?></span>
                            <span class="pager-next"><?= $text ? $text : __('Previous') ?></span>
                            <img class="previous" src="<?= $mediaUrl ?>images/icon/previous.png"/>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($block->canShowFirst()): ?>
                    <li class="item">
                        <a class="page first" href="<?= $block->getFirstPageUrl() ?>">
                            <span class="label"><?= __('Page') ?></span>
                            <span>1</span>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($block->canShowPreviousJump()): ?>
                    <li class="item">
                        <a class="page previous jump" title="" href="<?= $block->getPreviousJumpUrl() ?>">
                            <span>...</span>
                        </a>
                    </li>
                <?php endif;?>

                <?php foreach ($block->getFramePages() as $_page): ?>
                    <?php if ($block->isPageCurrent($_page)): ?>
                        <li class="item current">
                            <strong class="page">
                                <span class="label"><?= __('You\'re currently reading page') ?></span>
                                <span><?= $_page ?></span>
                            </strong>
                        </li>

                    <?php else: ?>
                        <li class="item">
                            <a href="<?= $block->getPageUrl($_page) ?>" class="page">
                                <span class="label"><?= __('Page') ?></span>
                                <span><?= $_page ?></span>
                            </a>
                        </li>
                    <?php endif;?>
                <?php endforeach;?>

                <?php if ($block->canShowNextJump()): ?>
                    <li class="item">
                        <a class="page next jump" title="" href="<?= $block->getNextJumpUrl() ?>">
                            <span>...</span>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($block->canShowLast()): ?>
                    <li class="item">
                        <a class="page last" href="<?= $block->getLastPageUrl() ?>">
                            <span class="label"><?= __('Page') ?></span>
                            <span><?= $block->getLastPageNum() ?></span>
                        </a>
                    </li>
                <?php endif;?>

                <?php if (!$block->isLastPage()): ?>
                    <li class="item pages-item-next">
                        <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                        <a class="<?= $text ? 'link ' : 'action '?> next" href="<?= $block->getNextPageUrl() ?>" title="<?= $text ? $text : __('Next') ?>">
                            <span class="label"><?= __('Page') ?></span>
                            <span class="pager-next"><?= $text ? $text : __('Next') ?></span>
                            <img class="next" src="<?= $mediaUrl ?>images/icon/next.png"/>
                        </a>
                    </li>

                <?php endif;?>
                <li class="item">
                    <a class="view-all" href="<?= $curUrl .'?product_list_limit=all' ?>"><p>   View All </p></a>
                </li>
            </ul>
        </div>
    <?php endif; ?>

    <?php if ($block->isShowPerPage()): ?>
        <div class="limiter">
            <strong class="limiter-label"><?= __('Show') ?></strong>
            <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <option value="<?= $block->getLimitUrl($_key) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                        selected="selected"<?php endif ?>>
                        <?= $_limit ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <span class="limiter-text"><?= __('per page') ?></span>
        </div>
    <?php endif ?>

    <?php if ($block->getUseContainer()): ?>
        </div>
    <?php endif ?>

<?php endif ?>
