<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>


<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of \Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>


<nav class="navigation" role="navigation" id="topMenuBar">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= $_menu; ?>

        <li class="level0 nav-4 level-top ui-menu-item" role="presentation">
            <a href="/lookbook" class="level-top ui-corner-all" id="ui-id-6" tabindex="-1" role="menuitem"><span>LOOKBOOK</span></a>
        </li>
        <li class="level0 nav-5 last level-top ui-menu-item" role="presentation">
            <a href="/press1" class="level-top ui-corner-all" id="ui-id-7" tabindex="-1"
               role="menuitem"><span>PRESS</span></a>
        </li>
    </ul>
</nav>


<?php
$categoryFactory = $_objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$allCat = $categoryFactory->create()
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('level', 2);

$style = "";
$i = 1;
foreach ($allCat as $cat) {
    $img = $cat->getImageUrl();
    if (isset($img) && !is_null($img)) {
        $style .= '#topMenuBar li.level0:nth-child(' . $i . ') > .submenu:before { background: url("' . $img . '") no-repeat 0 0;'.
        '-webkit-background-size: contain; -moz-background-size: contain; -o-background-size: contain; background-size: contain; }';
        $i++;
    }
}

?>

<style>
    <?= $style ?>
</style>
