<?php /*
<div class="IQbanner top">
    <div class="inner">        
        <?php 
        $baseurl = $this->getBaseUrl(); 
        $banners = $this->getHomeContentcollection(); 
        $i=1;
            foreach ($banners as $banner): ?>
            <div class="banner_<?php echo $i; ?>">
                <h5><?php echo $banner['name']; ?></h5>
                <?php if(!empty($banner['link'])): ?>
                <a href="<?php echo $banner['link'];  ?>"><img src="<?php echo $baseurl.$banner['image']; ?>"></a>
                <?php else :?>
                <img src="<?php echo $baseurl.$banner['image']; ?>">
                <?php endif; ?>
                <p>
                    <?php echo $banner['details']; ?>
                </p>  
            </div>   
        <?php $i++; endforeach; ?>      
    </div>
</div>
*/?>
<?php /*
<?php 
$mediaUrl = $this->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$baseurl = $this->getBaseUrl(); 
$collection = $this->getHomeContentcollection(); 
?>
    <div id="bannerHS" class="carousel slide" data-ride="carousel" data-interval="false">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <?php $i = 1; ?>
            <?php foreach($collection as $bn) { ?>
                <div class="item <?= ($i == 1) ? 'active':'' ?>">
                    <img src="<?= $mediaUrl . $bn['image']?>" />
                </div>
                <?php $i++; ?>
            <?php } ?>
        </div>
        <!-- Controls -->
        <a href="#bannerHS" role="button" data-slide="prev">
            <div class="prevButtonWrap" aria-hidden="true">
                <img src="<?= $mediaUrl ?>images/home/left-big.png"/>
            </div>
        </a>
        <a href="#bannerHS" role="button" data-slide="next">
            <div class="nextButtonWrap" aria-hidden="true">
                <img src="<?= $mediaUrl ?>images/home/right-big.png"/>
            </div>
        </a>

        <!-- Indicators -->
        <ol class="carousel-indicators">
            <?php $i =0 ?>
            <?php foreach($collection as $bn) { ?>
                <li data-target="#bannerHS" data-slide-to="<?= $i ?>" class="<?= ($i == 0) ? 'active':'' ?>"></li>
                <?php $i++; ?>
            <?php } ?>
        </ol>
    </div>
 <script type="text/javascript" src="/pub/js/carousel.js"></script>
 */?>