<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search">
    <div class="block block-title"><strong><?= __('Search'); ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?= $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <label id="clickSearchIcon" class="label" for="search" data-role="minisearch-label">
                    <span><?= __('Search'); ?></span>
                </label>
                <div class="control" id="searchControl" data-role="dropdownDialog">
                    <div id="searchControlWrapper">
                        <span class="" id="closeSearch">Close X</span>
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                                    "formSelector":"#search_mini_form",
                                    "url":"<?= $block->getUrl('search/ajax/suggest'); ?>",
                                    "destinationSelector":"#search_autocomplete"}
                               }'
                               type="text"
                               name="<?= $helper->getQueryParamName() ?>"
                               value="<?= $helper->getEscapedQueryText() ?>"
                               placeholder="<?= __('Search by product name. keywords, etc.'); ?>"
                               class="input-text"
                               maxlength="<?= $helper->getMaxQueryLength();?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?= __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>


<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            $('#clickSearchIcon').click(function(){
                $('#searchControl').toggle();
            });

            $('#closeSearch').click(function() {
                $('#searchControl').css("display","none");
            });
        });
    });
</script>