<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);


switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int)$block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('YOU MAY ALSO LIKE');
            $items = $block->getItems();
            $limit = 12;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int)$block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Up sell');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
?>

<div class="otherSliderWrapper <?= $type ?>">
    <?php if ($exist): ?>
        <?php if ($type == 'related' || $type == 'upsell'): ?>
            <div class="otherSliderInner">
                <p class="titDetailSlider"><?= $title ?></p>
                <div id="<?= $type ?>Slider" class="carousel slide productSlider" data-ride="carousel" data-interval="false">
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner padHS " role="listbox">
                        <!-- Items -->
                        <?php $i = 1; ?>
                        <?php foreach ($items as $newPro) { ?>
                            <?php if ($i % 4 == 1) { ?>
                        <div class="item <?= ($i == 1) ? ' active' : '' ?>">
                            <div class="row">
                            <?php } ?>

                            <div class="HS-item-Resp">
                                <div class="HS-item-wrap">
                                    <a href="<?= $newPro->getProductUrl() ?>">
                                        <div class="img-resp img150">
                                            <img class="fullHeight" src="<?= $mediaUrl . 'catalog/product' . $newPro->getThumbnail() ?>"/>
                                        </div>
                                        <p class="titPSlide hidden"><?= $newPro->getName() ?></p>
                                        <p class="pricePSlide hidden">
                                            <?php
                                            if ($newPro->getTypeId() == 'configurable') {
                                                $price = ($newPro->getMinPrice() == $newPro->getMaxPrice()) ?
                                                    "$" . number_format($newPro->getMinPrice(), 2) :
                                                    "$".number_format($newPro->getMinPrice(), 2). " - $".number_format($newPro->getMaxPrice(), 2);
                                                echo $price;
                                            } else { ?>
                                                <?= "$" . number_format($newPro->getFinalPrice(), 2) ?>
                                                <?php if ($newPro->getFinalPrice() != $newPro->getPrice()) { ?>
                                                    <span class="oldPrice"><?= "$" . number_format($newPro->getPrice(), 2) ?></span>
                                                <?php } ?>
                                            <?php } ?>
                                        </p>
                                    </a>
                                </div>
                            </div>

                            <?php if ($i % 4 == 0 || $i == $exist) { ?>
                            </div>
                        </div>
                            <?php } ?>

                            <?php $i++; ?>
                        <?php } ?>
                    </div>

                    <!-- Controls -->
                    <a href="#<?= $type ?>Slider" role="button" data-slide="prev">
                        <div class="prevButtonWrap slideCtr" aria-hidden="true">
                            <img src="<?= $mediaUrl ?>images/icon/pLeft.png"/>
                        </div>
                    </a>
                    <a href="#<?= $type ?>Slider" role="button" data-slide="next">
                        <div class="nextButtonWrap slideCtr" aria-hidden="true">
                            <img src="<?= $mediaUrl ?>images/icon/pRight.png"/>
                        </div>
                    </a>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>


