<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?= __('Availability') ?>">
            <span><?= __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?= __('Availability') ?>">
            <span><?= __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
