<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<div class="shortDes"><?= $_product->getShortDes() ?></div>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if (!$_product->isAvailable()): ?>
        <div class="stock unavailable" title="<?= __('Availability') ?>">
            <span><?= __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
