<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of \Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$curUrl = explode("?", $currentStore->getCurrentUrl())[0];
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
?>

<?php $_product = $block->getProduct() ?>

<?php
    $desP = $_product->getName() . " - " . $_product->getShortDes();
    $img = urlencode($mediaUrl . 'catalog/product' . $_product->getThumbnail());
    $des = urlencode($_product->getShortDes());
    $url = urlencode($curUrl);
?>

<div>
    <a href="javascript:void(0)">
        <img src="<?= $mediaUrl ?>/images/icon/social/sns_insta.png"/>
    </a>
    <a href="http://www.facebook.com/sharer.php?u=<?= $url ?>" target="_blank">
        <img src="<?= $mediaUrl ?>/images/icon/social/sns_fb.png"/>
    </a>
    <a href="http://pinterest.com/pin/create/button/?url=<?= $url ?>&media=<?= $img ?>&description=<?= $desP ?>" target="_blank">
        <img src="<?= $mediaUrl ?>/images/icon/social/sns_pin.png"/>
    </a>
</div>

<!--<script type="text/javascript" src="http://assets.pinterest.com/js/pinit.js"></script>-->